name: Build
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build and analyze
        run: ./gradlew clean build dokkaGfmMultiModule
      - name: Publish Dokka
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /
          cd /home/runner/work/xlitekt/xlitekt/
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dokka/*
          git commit -m "Update Dokka."
          git push https://$USERNAME:$REPO_KEY@github.com/runetopic/xlitekt.git